# Generated by Django 5.1.3 on 2025-05-27 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_search_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='latitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='search',
            name='longitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
